name: Java CI pipeline

on:
  push:
    branches: [ "ci-cd-workflows" ]
 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        

    - name: Build with Maven
      run: mvn clean package
   

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: petclinic-war
        path: "target/petclinic.war"
        if-no-files-found: error
    
    

